name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: build
      run: docker-compose -f docker-compose.test.yml build

    - name: sut
      run: docker-compose -f docker-compose.test.yml sut
